# Generated by Django 3.2.7 on 2021-10-17 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ORDER', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivery_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_executive', to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(to='ORDER.Order')),
            ],
            options={
                'db_table': 'tbl_assigned_order',
            },
        ),
    ]
