# Generated by Django 3.2.7 on 2021-10-17 07:07

import ORDER.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PRODUCT', '0001_initial'),
        ('ACCOUNT', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=ORDER.models.generate_order_id, editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='ORDER ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('datetimestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'SUCCESS'), ('pending', 'PENDING'), ('failed', 'FAILED')], max_length=10)),
                ('delivery_status', models.CharField(max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='ACCOUNT.deliveryaddress')),
                ('product', models.ManyToManyField(related_name='order_product', to='PRODUCT.Product')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_order',
                'ordering': ['-datetimestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='ORDER.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.product')),
            ],
            options={
                'db_table': 'tbl_order_detail',
            },
        ),
    ]
